import type { Metadata } from 'next'
import { Header } from '../components/shared/Header/Header'
import { Footer } from '../components/shared/Footer'
import { Roboto } from 'next/font/google'
import '../app/globals.css'
import '../scss/globals.scss'
import dynamic from 'next/dynamic'
const ToastContainer = dynamic(() => import('app/components/Toast/ToastContainer'), { ssr: false })

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex-layout`}>
        <ToastContainer />
        <Header />
        <main className="flex-grow">
          <div className="container">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
